spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
invoicing-system:
  database: jpa
