invoicing-system:
  database: sql
spring:
  jpa:
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    user: sa
    password: sa
    driverClassName: org.h2.Driver




